name: TMScanner Scan
description: Scan your sol files
#
inputs:
  tm_url:
    description: URL of TMScanner
    required: true
  tm_repository_id:
    description: Repository Id in TMScanner
    required: true    
  tm_file:
    description: The file to be sent to TMScanner
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.tm_url }}
    - ${{ inputs.tm_repository_id }}
    - ${{ inputs.tm_file }}        
#
branding:
  icon: check
  color: green